

CREATE TABLE public.product (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	brand varchar(255) NULL,
	category varchar(255) NULL,
	limitby int4 NULL,
	relevancy_score float8 NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE public.shopper (
	id varchar(255) NOT NULL,
	CONSTRAINT shopper_pkey PRIMARY KEY (id)
);

CREATE TABLE public.shopper_product (
	shopper_entity_id varchar(255) NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT uk_j6kmnnyvqf655hmnq7b60nd35 UNIQUE (product_id)
);


-- public.shopper_product foreign keys

ALTER TABLE public.shopper_product ADD CONSTRAINT fkbhqr375u256offgij6jux9s2 FOREIGN KEY (product_id) REFERENCES public.product(id);
ALTER TABLE public.shopper_product ADD CONSTRAINT fkowevkdl50o2eaoejismgsdhhf FOREIGN KEY (shopper_entity_id) REFERENCES public.shopper(id);